default_language: en
output:
  folder: history
news_api:
  base_url: https://newsapi.org/v2/
  endpoint: everything
  sort_type: relevancy
  language: en
  from_date:
    months_before: 1
hugging_face:
  model: facebook/bart-large-cnn
  max_length: 100
  min_length: 30
  do_sample: False


